// src/components/ExternalLink.tsx
import type { FC } from 'react';
import { Link, type LinkProps } from '@mui/material';

type ExternalLinkProps = LinkProps & {
  href: string;
};

const ExternalLink: FC<ExternalLinkProps> = ({ children, ...props }) => {
  return (
    <Link target="_blank" rel="noreferrer" {...props}>
      {children ?? props.href}
    </Link>
  );
};

export default ExternalLink;

// src/components/ExternalLink.svelte
<script lang='ts'>
  import type { Snippet } from 'svelte';
  import type { HTMLAnchorAttributes } from 'svelte/elements';
  import { ExternalLinkIcon } from '@lucide/svelte';

  export type ExternalLinkProps = HTMLAnchorAttributes & {
    href: string;
    children?: Snippet;
  };

  const { children, ...props }: ExternalLinkProps = $props();
</script>

<a target='_blank' rel='noreferrer' {...props}>
  {#if children}
    {@render children()}
  {:else}
    {props.href}
  {/if}
  <ExternalLinkIcon size='0.85em' />
</a>
