// src/options-ui/App.tsx
import type { FC } from 'react';
import type { UserOptions } from '../utils/sync-options';
import { Box, Button, Container, CssBaseline, Snackbar, ThemeProvider, Typography } from '@mui/material';
import { useCallback, useEffect, useState } from 'react';
import { defaultSyncOptions } from '../utils/default-options';
import { withRandomId } from '../utils/helpers';
import { getSyncStorage, setSyncStorage } from '../utils/storage';
import { SyncOptions } from '../utils/sync-options';
import theme from '../utils/theme';
import ConfirmationDialog from './ConfirmationDialog';
import Glossary from './Glossary';
import termSections from './term-sections';
import OptionsForm from './UserOptionsForm';

const App: FC = () => {
  const [initialSyncOptions, setInitialSyncOptions] = useState<SyncOptions>();
  const [snackbarOpen, setSnackbarOpen] = useState(false);
  const [dialogOpen, setDialogOpen] = useState(false);
  const [syncOptionsLoadingFailed, setSyncOptionsLoadingFailed] = useState<boolean>();

  useEffect(() => {
    getSyncStorage('options')
      .then((unknownStorage) => {
        const syncOptions = SyncOptions.parse(unknownStorage.options);
        setInitialSyncOptions(syncOptions);
        setSyncOptionsLoadingFailed(false);
      })
      .catch(() => {
        setSyncOptionsLoadingFailed(true);
      });
  }, []);

  const handleSubmit = useCallback(async (userOptions: UserOptions) => {
    if (!initialSyncOptions) {
      return;
    }

    await setSyncStorage({
      options: {
        ...initialSyncOptions,
        user: userOptions,
      },
    });

    setSnackbarOpen(true);
  }, [initialSyncOptions]);

  return (
    <ThemeProvider theme={theme}>
      <CssBaseline />
      <Container component="main">
        <Box component="section" sx={{ my: 3 }}>
          <Typography variant="h1">ZEN Study + オプション</Typography>
          {initialSyncOptions && (
            <OptionsForm
              defaultValues={initialSyncOptions.user}
              onSubmit={handleSubmit}
            />
          )}
          {syncOptionsLoadingFailed && (
            <Box sx={{ my: 2, color: 'error.main' }}>
              オプションの読み込みに失敗しました。リセットすることで解決することもできます。
            </Box>
          )}
          <Box sx={{ my: 2 }}>
            <Button
              variant="outlined"
              color="error"
              onClick={() => {
                setDialogOpen(true);
              }}
            >
              すべてのオプションをリセット
            </Button>
          </Box>
        </Box>
        <Box component="section" sx={{ my: 3 }}>
          <Typography variant="h2">用語</Typography>
          <Glossary
            termSections={termSections.map((section) => withRandomId({
              ...section,
              terms: section.terms.map(withRandomId),
            }))}
          />
        </Box>
        <Snackbar
          open={snackbarOpen}
          message="保存されました"
          autoHideDuration={3000}
          anchorOrigin={{ vertical: 'bottom', horizontal: 'right' }}
          onClose={(_event, reason) => {
            if (reason !== 'clickaway') {
              setSnackbarOpen(false);
            }
          }}
        />
        <ConfirmationDialog
          open={dialogOpen}
          title="本当にリセットしますか？"
          yes="リセット"
          no="キャンセル"
          onClose={(isConfirmed) => {
            if (isConfirmed) {
              setSyncStorage({ options: defaultSyncOptions });
            }

            setDialogOpen(false);
          }}
        />
      </Container>
    </ThemeProvider>
  );
};

export default App;

// src/options-ui/App.svelte
<script lang='ts'>
  import { defaultSyncOptions } from '../utils/default-options';
  import { getSyncStorage, setSyncStorage } from '../utils/storage';
  import { SyncOptions, UserOptions } from '../utils/sync-options';
  import ConfirmationDialog from './ConfirmationDialog.svelte';
  import Glossary from './Glossary.svx';
  import OptionsForm from './options-form/OptionsForm.svelte';
  import './app.scss';

  let initialSyncOptions = $state<SyncOptions>();
  let syncOptionsLoadingFailed = $state(false);

  const loadSyncOptions = async () => {
    try {
      const unknownStorage = await getSyncStorage('options');
      initialSyncOptions = SyncOptions.parse(unknownStorage.options);
    } catch {
      syncOptionsLoadingFailed = true;
    }
  };

  $effect(() => {
    loadSyncOptions();
  });

  let resetDialogOpen = $state(false);

  const onSubmit = async (userOptions: UserOptions) => {
    if (!initialSyncOptions) {
      return;
    }

    await setSyncStorage({
      options: {
        ...initialSyncOptions,
        user: userOptions,
      },
    });
  };
</script>

<main class='container'>
  <section>
    <h1>ZEN Study + オプション</h1>
    {#if initialSyncOptions}
      {#key initialSyncOptions}
        <OptionsForm
          initialOptions={initialSyncOptions.user}
          {onSubmit}
        />
      {/key}
    {:else if !syncOptionsLoadingFailed}
      <p aria-busy='true'>オプションを読み込み中</p>
    {/if}
    {#if syncOptionsLoadingFailed}
      <p class='error'>
        オプションの読み込みに失敗しました。リセットすることで解決することもできます。
      </p>
    {/if}
    <p>
      <button
        type='button'
        class='secondary'
        onclick={() => {
          resetDialogOpen = true;
        }}
      >
        すべてのオプションをリセット
      </button>
    </p>
  </section>
  <section>
    <h2>用語</h2>
    <Glossary />
  </section>
  <ConfirmationDialog
    open={resetDialogOpen}
    yes='リセット'
    no='キャンセル'
    onclose={(isConfirmed) => {
      if (isConfirmed) {
        setSyncStorage({ options: defaultSyncOptions }).then(() => {
          loadSyncOptions();
        });
      }

      resetDialogOpen = false;
    }}
  >
    <h2>オプションのリセット</h2>
    <p>本当にリセットしますか？</p>
  </ConfirmationDialog>
</main>

<style>
  .error {
    color: var(--pico-del-color);
  }
</style>
